name: Compile and Lint
on:
  pull_request:
jobs:
  compile_and_lint:
    runs-on: ubuntu-latest
    name: Compile and Lint
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '22.17.1'
      - run: yarn install --frozen-lockfile
      - run: npx nuxi typecheck
      - run: yarn lint:js
